CREATE TABLE IF NOT EXISTS modmail_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id BIGINT,
    channel_id BIGINT UNIQUE,
    user_id BIGINT,
    reason TEXT,
    claimed_by BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_modmail_sessions_guild_id ON modmail_sessions (guild_id);
CREATE INDEX IF NOT EXISTS idx_modmail_sessions_user_id ON modmail_sessions (user_id);